os:
  - osx
  - linux
  - windows

language:
  - cpp

compiler:
  - gcc
  - clang

env:
  - BUILD_SHARED=ON
  - BUILD_SHARED=OFF

script:
  - mkdir build
  - cd build
  - cmake -DNOSTRA_BUILD_SHARED_TESTS=$BUILD_SHARED ..
  - cmake --build .
  - ctest -C Debug --output-on-failure
  